server:
  port: 8081
spring:
  application:
   name: user-service


  datasource:
    url: jdbc:postgresql://localhost:5432/foodX
    username: postgres
    password: Singama@98
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
